import Head from "next/head";
import Image from "next/image";
import ProductCard from "../components/ProductCard";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ProductCard
          productImage={
            "https://www.badeendwinkel.nl/8516-large_default/rubber-duck-ducky-65-cm-dr.jpg"
          }
          productName={"Rubber Duck"}
          price={4.99}
          addToCart={() => alert("Added to cart!")}
        />
        <ProductCard
          productImage={
            "https://www.amsterdamduckstore.com/wp-content/uploads/2021/07/Corona-Rubber-Duck-Yellow-slant-right-Amsterdam-Duck-Store.jpg"
          }
          productName={"Rubber Doc"}
          price={7.99}
          addToCart={() => alert("Added to cart!")}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
